### ISSUE TITLE
LLC dumps: over-subscribed slots

### ISSUE THREAD

**Issue by maerem** [unison-code/unison#2] opened 2017-02-15 09:36 UTC
**Command used to generate error:**
`llc -O3 -unison-verbose -unison-solver-flags="--local-portfolio f" -unison-no-clean -march=hexagon -mcpu=hexagonv4 -disable-post-ra -disable-tail-duplicate -disable-branch-fold -disable-block-placement -disable-phi-elim-edge-splitting -disable-hexagon-cfgopt -disable-if-conversion -o adpcm.unison.S adpcm.unison.ll`

**Output:**
[global] found optimal solution
execution time: 24642.9 ms
total failed nodes in all problems: 3686
total searched nodes in all problems: 10688
optimal solution has cost 9741
upper bound: 9906, improvement: 1.7%
`/home/martip/bin/uni: uni export --target=Hexagon /tmp/unison-4db3ce.alt.uni -o /tmp/unison-4db3ce.unison.mir --basefile=/tmp/unison-4db3ce.llvm.mir --solfile=/tmp/unison-4db3ce.out.json`
over-subscribed slots
UNREACHABLE executed at 

> /home/martip/llvm/lib/Target/Hexagon/MCTargetDesc/HexagonMCShuffler.cpp:141!
> 0  llc             0x00000000028c8485 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 59
> 1  llc             0x00000000028c87dd
> 2  llc             0x00000000028c6c23 llvm::sys::RunSignalHandlers() + 153
> 3  llc             0x00000000028c7dcc
> 4  libpthread.so.0 0x00007f9bb4f5b3d0
> 5  libc.so.6       0x00007f9bb3ee8418 gsignal + 56
> 6  libc.so.6       0x00007f9bb3eea01a abort + 362
> 7  llc             0x00000000028a6d32
> 8  llc             0x00000000011b8a80 llvm::HexagonMCShuffle(llvm::MCInstrInfo const&, llvm::MCSubtargetInfo const&, llvm::MCInst&) + 582
> 9  llc             0x00000000011b4ffa llvm::HexagonMCInstrInfo::canonicalizePacket(llvm::MCInstrInfo const&, llvm::MCSubtargetInfo const&, llvm::MCContext&, llvm::MCInst&, llvm::HexagonMCChecker*) + 211
> 10 llc             0x000000000103a4b9 llvm::HexagonAsmPrinter::EmitInstruction(llvm::MachineInstr const*) + 575
> 11 llc             0x0000000001d1ffb6 llvm::AsmPrinter::EmitFunctionBody() + 1404
> 12 llc             0x0000000000dcf627
> 13 llc             0x0000000001037951
> 14 llc             0x0000000001edde45 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) + 95
> 15 llc             0x00000000027de83c llvm::FPPassManager::runOnFunction(llvm::Function&) + 330
> 16 llc             0x00000000027de9d5 llvm::FPPassManager::runOnModule(llvm::Module&) + 133
> 17 llc             0x00000000027ded50
> 18 llc             0x00000000027df481 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 271
> 19 llc             0x00000000027df68d llvm::legacy::PassManager::run(llvm::Module&) + 39
> 20 llc             0x0000000000d68acc
> 21 llc             0x0000000000d675f8 main + 261
> 22 libc.so.6       0x00007f9bb3ed3830 __libc_start_main + 240
> 23 llc             0x0000000000d63369 _start + 41

Stack dump:
`0.      Program arguments: /home/martip/llvm/build/Debug+Asserts/bin/llc -O3 -unison-verbose -unison-solver-flags=--local-portfolio f -unison-no-clean -march=hexagon -mcpu=hexagonv4 -disable-post-ra -disable-tail-duplicate -disable-branch-fold -disable-block-placement -disable-phi-elim-edge-splitting -disable-hexagon-cfgopt -disable-if-conversion -o adpcm.unison.S adpcm.unison.ll`
`1.      Running pass 'Function Pass Manager' on module 'adpcm.unison.ll'.`
`2.      Running pass 'Hexagon Assembly Printer' on function '@adpcm_coder'`
Aborted (core dumped)
Makefile:79: recipe for target 'adpcm.unison.S' failed

[adpcm.zip](https://github.com/unison-code/unison/files/776587/adpcm.zip)

**Comment by robcasloz** [comment] 2017-02-21 10:06
Hi @maerem, thanks for the report! Closing since I cannot reproduce the failure, most likely commit 56b3e1bf4931d7955f1ce81f4e6ef06bf0dbc775 fixed the issue.

**Closed by robcasloz** 2017-02-21 10:06 UTC
