### ISSUE TITLE
Basic block executing twice as often - Benchmark: djpeg, Function: h2v2_fancy_upsample

### ISSUE THREAD

**Issue by maerem** [unison-code/unison#20] opened 2017-04-20 13:26 UTC
When executing the simulator without hardware stalls (timings) the simulator crashes:

> Hexagon-sim INFO: the rev_id used in the simulation is 0x00000084 (v4m)
> CRASH from thread 0!
> I think the exception was: 0x15, Invalid packet
> 
> Register Dump (r0 clobbered, pc subject to prior action by the exception handler):
> r00=000000cd r01=0002ccd8 r02=0002ec34 r03=00000002
> r04=00000004 r05=00012e20 r06=00000083 r07=00000831
> r08=00012e22 r09=0000020d r10=0000083b r11=00032d02
> r12=000007f3 r13=00032c8a r14=0000020d r15=0000020d
> r16=0412b010 r17=0002eadc r18=0412af64 r19=0002cd4c
> r20=0002eb04 r21=0002cd2c r22=0002e5c0 r23=00000001
> r24=0002e600 r25=00000003 r26=babebeef r27=babebeef
> r28=00000000 r29=0412af00 r30=0412af28 r31=00012db4
> sa0=00013670 lc0=00000001 sa1=0000d2f0 lc1=00000001
> p30=ff000000  m0=00000000  m1=00000000 usr=00010000
>  pc=00000894 ugp=00000000  gp=0002b000 elr=00012dc0
> badva0=0412b1f8 badva1=00000000
> ssr=00340015 ccr=00130000 tid=00000000 imask=00000000
> evb=00005000 modectl=00000001 syscfg=0083007f ipend=00000000
> 
> Memory hex dump close to the top of the stack in byte-order:
>  -- unable to figure out the stack size, assuming 0x100000
>  stack-bottom: 0x0412b200 stack-top: 0x0412af00
> 0x0412af00: efbebeba efbebeba e0ea0200 efbebeba
> 0x0412af10: 01000000 a8ea0200 4ccd0200 dcea0200
> 0x0412af20: 10b01204 64af1204 58af1204 34f00000
> 0x0412af30: 01000000 efbebeba efbebeba efbebeba
> 0x0412af40: efbebeba efbebeba 01000000 07000000
> 0x0412af50: 10b01204 4ccd0200 78af1204 249a0000
> 0x0412af60: 78af1204 00000000 30cd0200 07000000
> 0x0412af70: 28b90200 80b90200 e8b11204 d8520000
> 0x0412af80: 1f1f1f1f 1f1f1f1f 1f1f1f1f 90970100
> 0x0412af90: c0970100 20980100 50980100 40990100
> 0x0412afa0: 68000000 00000000 3f000000 00000000
> 0x0412afb0: 00000000 00000000 01000000 02000000
> 0x0412afc0: 77000000 1f1f1f1f 1f1f1f1f 1f1f1f1f
> 0x0412afd0: 1f1f1f1f 1f1f1f1f 1f1f1f1f 1f1f1f1f
> 0x0412afe0: 1f1f1f1f 1f1f1f1f 1f1f1f1f 1f1f1f1f
> 0x0412aff0: 1f1f1f1f 00000000 00000000 a8830200
> 0x0412b000: 77000000 28600200 e8030000 13040000
> 0x0412b010: 8caf1204 08b20200 00000000 01000000
> 0x0412b020: cd000000 f0b20200 e3000000 95000000
> 0x0412b030: 03000000 03020000 01000000 01000000
> 0x0412b040: 00000000 0000f03f 00000000 00000000
> 0x0412b050: 00000000 01000000 01000000 00000000
> 0x0412b060: 02000000 01000000 00010000 00000000
> 0x0412b070: 00000000 00000000 e3000000 95000000
> 0x0412b080: 03000000 03000000 01000000 00000000
> 0x0412b090: 00000000 00000000 01000000 01000000
> 0x0412b0a0: 01000000 01000000 00000000 18b30200
> 0x0412b0b0: a0b30200 00000000 00000000 28b40200
> 0x0412b0c0: 58b60200 00000000 00000000 40b50200
> 0x0412b0d0: 70b70200 00000000 00000000 08000000
> 0x0412b0e0: 30cc0200 00000000 00000000 00000000
> 0x0412b0f0: 00000000 00000000 00000000 01010101
> 0x0412b100: 01010101 01010101 01010101 05050505
> 0x0412b110: 05050505 05050505 05050505 00000000
> 0x0412b120: 01000000 00000100 01000000 00000000
> 0x0412b130: 00000000 00000000 02000000 02000000
> 0x0412b140: 08000000 0a000000 28d10200 03000000
> 0x0412b150: 30cc0200 84cc0200 d8cc0200 00000000
> 0x0412b160: 0f000000 0a000000 06000000 00000000
> 0x0412b170: 00000000 00000000 00000000 01000000
> 0x0412b180: 02000000 00000000 00000000 00000000
> 0x0412b190: 00000000 00000000 3f000000 00000000
> 0x0412b1a0: 00000000 00000000 08d00200 a8ea0200
> 0x0412b1b0: 30ea0200 70e60200 d0b20200 70b20200
> 0x0412b1c0: e8e90200 90e60200 c0e50200 a8d50200
> 0x0412b1d0: 00000000 00000000 efbebeba efbebeba
> 0x0412b1e0: 404c0200 07000000 f8b11204 b8b80100
> 0x0412b1f0: efbebeba efbebeba 00000000 a83c0000

When executing with timings the basicblock .LBB7_3 and "onwards" seems to execute twice as often compared to the LLVM-solution.

> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1179: (h2v2_fancy_upsample:0x13220) 150 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1179: (h2v2_fancy_upsample:0x13220) 173 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1183: (h2v2_fancy_upsample:0x13224) 150 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1188: (h2v2_fancy_upsample:0x1322c) 150 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1193: (h2v2_fancy_upsample:0x13234) 150 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1197: (h2v2_fancy_upsample:0x13240) 150 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1202: (.LBB7_2:0x13244) 150 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1206: (.LBB7_2:0x13248) 150 executions
### Here it starts executing twice as often
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1216: (.LBB7_3:0x1324c) 455 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1221: (.LBB7_3:0x13254) 372 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1226: (.LBB7_3:0x13260) 399 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1230: (.LBB7_3:0x1326c) 354 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1235: (.LBB7_3:0x13274) 300 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1241: (.LBB7_3:0x1327c) 323 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1247: (.LBB7_3:0x1328c) 300 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1251: (.LBB7_3:0x1329c) 300 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1255: (.LBB7_3:0x132a4) 300 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1258: (.LBB7_3:0x132ac) 400 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1262: (.LBB7_3:0x132b0) 300 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1266: (.LBB7_3:0x132b8) 300 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1271: (.LBB7_5:0x132bc) 600 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1275: (.LBB7_5:0x132c4) 301 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1282: (.LBB7_5:0x132cc) 305 executions
> /home/martip/benchmarks/jpeg/djpeg/unison_build_h2v2_fancy_upsample_43/jdsample.S:1286: (.LBB7_5:0x132dc) 324 executions
> ...

In the attached zip-file you find folders for the "correct" unison code, the incorrect code which executes twice as often, and the llvm solution. Each contains the generated assembly-code together with a text-file which describes the number of cycles spend in each bundle. 

The original c source file is in the root of the zip file.

[djpeg-h2v2_fancy_upsample.zip](https://github.com/unison-code/unison/files/943194/djpeg-h2v2_fancy_upsample.zip)

**Comment by maerem** [comment] 2017-04-21 13:09
Command used to invoke llc/unison:
`llc -O3 -unison-no-clean -unison-import-flags="--simplifycontrolflow=false" -unison-normalize-flags="--simplifycontrolflow=false" -unison-verbose -unison-solver-flags="--emit-improvement" -unison-max-instrs=1000 -unison-model-flags="--strictlybetter=false" -unison-single-function=h2v2_fancy_upsample  -march=hexagon -mcpu=hexagonv4 -disable-post-ra -disable-tail-duplicate -disable-branch-fold -disable-block-placement -disable-phi-elim-edge-splitting -disable-hexagon-cfgopt -disable-if-conversion -o unison_build_h2v2_fancy_upsample_43/jdsample.S unison_build_h2v2_fancy_upsample_43/jdsample.ll`

jdsample.ll is provided in the attached zip-file
[jdsample.zip](https://github.com/unison-code/unison/files/947113/jdsample.zip)

**Comment by robcasloz** [comment] 2017-08-29 13:57
Cannot reproduce it anymore, djpeg produces now correct results. The bug has probably been addressed by commit 63ad196 or 9e8253d.

**Closed by robcasloz** 2017-08-29 13:57 UTC
