### ISSUE TITLE
Incorrect result - Benchmark: g721_encode, Function: g721_encoder

### ISSUE THREAD

**Issue by maerem** [unison-code/unison#11] opened 2017-03-03 10:37 UTC
The different assembly-files and the source c-file are attached in the zip-file provided. The output is also provided.

[g721_encode-g721_encoder-incorrect_result.zip](https://github.com/unison-code/unison/files/816498/g721_encode-g721_encoder-incorrect_result.zip)

**Comment by robcasloz** [comment] 2017-08-29 13:46
Cannot reproduce it anymore, g721-encode produces now correct results. The bug has probably been addressed by commit 63ad19639ead7fbf0e60cf289d1e4de2263ac0fb or 9e8253dfc578a466670a27b443ee571fed081bd6.

**Closed by robcasloz** 2017-08-29 13:46 UTC
