### ISSUE TITLE
Problem with ISA in main.

### ISSUE THREAD

**Issue by koukos** [unison-code/unison#17] opened 2017-03-10 09:35 UTC
After the latest update, unison generates a binary for ARM v7.
However, there is an issue in main in the assertion of argc. I am not sure if it has to do with the instruction itself that is 16bit type bne.n or with the registers selected. It seems more of an instruction issue to me. Incompatibility with the old ISA. Please find attached full source code and the disassembly of both llvm default and unison binaries (they are fairly small) : .dump files. The MIR directories contains mir from different runs including FDO.
[test.factorial.zip](https://github.com/unison-code/unison/files/833470/test.factorial.zip)

**Comment by koukos** [comment] 2017-03-10 14:03
Execution dump. Sorry i forgot to attach at the previous report.

koukos@RPi-0:~/Workspace/test.factorial$ ./factorial-llvm 6
factorial of 6 is: 720
koukos@RPi-0:~/Workspace/test.factorial$ ./factorial-unison 6
factorial-unison: factorial.c:22: int main(int, char **): Assertion `argc == 2' failed.
Aborted (core dumped)

**Comment by robcasloz** [comment] 2017-03-10 22:15
Thanks @koukos! How do you exactly invoke your makefiles to produce `factorial-llvm` and `factorial-unison`? I am not sure whether the problem is due to Unison or due to mixing different processor configurations during compilation.

**Comment by koukos** [comment] 2017-03-10 22:24
Thanks a lot Roberto. Please see the attached .zip file. It contains several Makefiles. Makefile.unison is the one that generates both binaries. Exactly the same flags are used "in some sense ..." for both. For unison we also append these flags:
MCPU_FLAGS=-mcpu=arm1156t2f-s -mattr=+thumb-mode (the only ones supported for ARM) and this is where the problem comes from. There is no bug in the instruction selection mechanism. Apologies for the misunderstanding. I think is the ARM ISA instructions that we use that might create the problem in the specific architecture, more specifically the +thumb-mode. Any workarounds to suggest for that?

**Comment by robcasloz** [comment] 2017-03-16 21:44
Closing as this is not a Unison-specific issue, @koukos let's keep this discussion offline.

**Closed by robcasloz** 2017-03-16 21:44 UTC
